name: Prepare v86 Engine

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare-v86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout WebFusion
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p vendor/v86
          mkdir -p vendor/v86/bios

          - name: Download Linux test image
        run: |
          mkdir -p vendor/v86/images

          curl -fL \
            https://i.copy.sh/linux.iso \
            -o vendor/v86/images/linux.iso

          ls -lh vendor/v86/images/linux.iso
        run: |
          curl -fL \
            https://github.com/copy/v86/releases/download/latest/libv86.js \
            -o vendor/v86/libv86.js

          curl -fL \
            https://github.com/copy/v86/releases/download/latest/v86.wasm \
            -o vendor/v86/v86.wasm

      - name: Download official BIOS files
        run: |
          curl -fL \
            https://github.com/copy/v86/archive/refs/tags/latest.tar.gz \
            -o v86.tar.gz

          tar -xzf v86.tar.gz

          cp v86-latest/bios/seabios.bin \
             vendor/v86/bios/seabios.bin

          cp v86-latest/bios/vgabios.bin \
             vendor/v86/bios/vgabios.bin

          rm -rf v86-latest v86.tar.gz

      - name: Verify files
        run: |
          ls -lh vendor/v86
          ls -lh vendor/v86/bios

      - name: Commit engine
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add vendor/v86

          git diff --cached --quiet || \
          git commit -m "Use official v86 release"

          git push
