name: Prepare v86 Engine

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare-v86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout WebFusion
        uses: actions/checkout@v4

      - name: Create v86 folders
        run: |
          mkdir -p vendor/v86/build
          mkdir -p vendor/v86/bios

      - name: Download v86 JavaScript engine
        run: |
          curl -L \
            https://raw.githubusercontent.com/copy/v86/master/build/libv86.js \
            -o vendor/v86/build/libv86.js

      - name: Download v86 WebAssembly engine
        run: |
          curl -L \
            https://raw.githubusercontent.com/copy/v86/master/build/v86.wasm \
            -o vendor/v86/build/v86.wasm

      - name: Download SeaBIOS
        run: |
          curl -L \
            https://raw.githubusercontent.com/copy/v86/master/bios/seabios.bin \
            -o vendor/v86/bios/seabios.bin

      - name: Download VGA BIOS
        run: |
          curl -L \
            https://raw.githubusercontent.com/copy/v86/master/bios/vgabios.bin \
            -o vendor/v86/bios/vgabios.bin

      - name: Commit v86 engine
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add vendor/v86

          git diff --cached --quiet || \
          git commit -m "Add v86 emulator engine"

          git push
